#!/bin/bash

docker run \
  --rm -it \
  -e CATTLE_URL=$CATTLE_URL \
  -e CATTLE_ACCESS_KEY=$CATTLE_ACCESS_KEY \
  -e CATTLE_SECRET_KEY=$CATTLE_SECRET_KEY \
  -e CATTLE_ENVIRONMENT=$CATTLE_ENVIRONMENT \
  --entrypoint=/usr/local/bin/etcd-rancher-operator \
    $IMAGE \
      -logtostderr=true \
      $@
